### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by sdhunt** [SCstevie/prj-rev-bwfs-dasmoto#2]
Your HTML code is clean, well structured, and nicely laid out. It truly is a pleasure to look at.
Awesome job!

However, imagine my surprise when I was expecting _Dasmoto's Arts & Crafts_, and was instead presented with this beautiful desert island paradise :)

**Comment by SCstevie** [comment]
Thank You,
I think I am finally understanding how this class works.
